name: ApexLikePing
main: net.st915.apexlikeping.ApexLikePing
version: 1.0.0
description: "A plugin that provides Apex Legends' Ping to Minecraft."
api-version: 1.19
author: stouma915

commands:
  ping:
    description: "Send Ping."
    usage: "/ping"
    permission: apexlikeping.use
    permission-message: "You don't have permission."

permissions:
  apexlikeping.*:
    default: op
    children:
      apexlikeping.use: true
  apexlikeping.use:
    description: "Allow pinging."
    default: true
